chore: add scripts to test TS and simplify annotation of reuse compoenets (#3382)
Signed-off-by: Christian Wolf <github@christianwolf.email>

diff --git a/.hooks/pre-push b/.hooks/pre-push
--- a/.hooks/pre-push
+++ b/.hooks/pre-push
@@ -107,6 +107,12 @@ then
 			echo "WARNING: The Stylelint check could not be carried out!"
 		fi
 
+		if [ -e 'node_modules/.bin/vue-tsc' ]; then
+			npm run type-check || { echo 'There was a problem with the TypeScript type checker.'; (( retVal |= 16 )); }
+		else
+			echo "WARNING: The TypeScript type check could not be carried out!"
+		fi
+
 		cd ../..
 	}
 
