Add error message with useful tips to solve linting issues
Signed-off-by: Christian Wolf <github@christianwolf.email>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -41,10 +41,20 @@ jobs:
             
         -   name: Check for formatting issues with vue files (prettier)
             shell: bash
-            run: npm run prettier
+            run: >-
+                npm run prettier || {
+                echo '::error ::The prettier style checker failed.
+                Please run `npm run prettier-fix` in order to correct this.';
+                exit 1;
+                }
         -   name: Check for formatting issues with CSS files (stylelint)
             shell: bash
-            run: npm run stylelint
+            run: >-
+                npm run stylelint || {
+                echo '::error ::The stylelint checker failed.
+                Please run `npm run stylelint-fix` to help solving these issues if possible.';
+                exit 1;
+                }
         
   
   unit-tests:
